### PR TITLE
Incremtental test

### PR DESCRIPTION
**Pull request by pettersoderlund**
This is a:
- [ ] bug fix PR with no breaking changes
- [X] new functionality
- [ ] a breaking change

## Description & motivation
Hello! 
I have tried to implement at feature to solve https://github.com/mjirv/dbt-datamocktool/issues/40

I have chosen to to make the unit test of incrementality in a separate test metod from the existing unit test functionality. 

To use the incremental test the mocked "current state" of the incremental model is to supposed to be delivered to the function in the input mapping at the key of "this". 

I have tried to break out some methods from both get_unit_test_incremental_sql and get_unit_test_sql to DRY up the code but am not always sure of what i have done.. However integration tests works. 

I have changed some models in the integration tests to also test incremental unit test capability. 

So - how is  unit_test_incremental intend to work?
1. The test creates a copy of current state and creates a table. 
2. The test then creates a merge statement to the table created in step 1. 
3. The test compares output of merged table to expected.

## Checklist
- [x] I have verified that these changes work locally on the following warehouses (Note: it's okay if you do not have access to all warehouses, this helps us understand what has been covered)
    - [x] BigQuery
    - [ ] Postgres
    - [ ] Redshift
    - [ ] Snowflake
- [ ] I have updated the README.md (if applicable)
- [ ] I have added tests & descriptions to my macros (and models if applicable)

### CODE REVIEW

**Comment by mjirv** [comment]
@pettersoderlund thanks for submitting this! I'll review and get back to you

**Comment by gwalterr** [comment]
I've only taken a quick look, but don't see anything related to [incremental strategy](https://docs.getdbt.com/docs/build/incremental-models#about-incremental_strategy). Do you think that supporting the model's strategy (should be at `ns.graph_model.config.incremental_strategy`) is within the scope of this PR?

**Comment by pettersoderlund** [comment]
> I've only taken a quick look, but don't see anything related to [incremental strategy](https://docs.getdbt.com/docs/build/incremental-models#about-incremental_strategy). Do you think that supporting the model's strategy (should be at `ns.graph_model.config.incremental_strategy`) is within the scope of this PR?

I'd say that would be out of scope of this PR @gwalterr  - only merge strategy is supported. However it is not a bad idea to have an incremental_strategy check in the beginning of the test to be explicit about that it is only "merge" strategy that is currently supported. Additional strategies can then be gradually if we get this working.

**Review by mjirv — APPROVED** [review]
This is awesome. Thanks for doing this! Sorry it took me so long to approve.

**Pull request merged**
