### PR TITLE
add support for dependson

### PR DESCRIPTION
**Pull request by chaimt**
This is a:
- [ ] bug fix PR with no breaking changes
- [ x] new functionality
- [ ] a breaking change

## Description & motivation
macros that have dynamic source tables must add hits for depends-on

## Checklist
- [ x] I have verified that these changes work locally on the following warehouses (Note: it's okay if you do not have access to all warehouses, this helps us understand what has been covered)
    - [ ] BigQuery
    - [ ] Postgres
    - [ ] Redshift
    - [ ] Snowflake
    - [ x] databricks 
- [ x] I have updated the README.md (if applicable)
- [ x] I have added tests & descriptions to my macros (and models if applicable)

### CODE REVIEW

**Review by mjirv — CHANGES_REQUESTED** [review]
Hi @chaimt, can you remove the .lh files that got included here somehow? Then I think we'll be good to merge this.

**Comment by chaimt** [comment]
done

**Comment by daveworth** [comment]
@mjirv - any thoughts on getting this merged?  I added this package to my dbt project just today to address some regressions in one of my models and ran into the need for the dependencies immediately.  I am more than happy to help get this over the line if there's any way I can.

**Comment by mjirv** [comment]
Hi @daveworth, yes, I'm looking at the merge conflicts now and will see if we can get this merged.

Could you share more info about the issues you're running into and what database you're on? I'd like datamocktool to "just work" without having to manually add dependencies if possible.

**Comment by mjirv** [comment]
@daveworth got it, thanks for sharing that. So are you mocking `ref('customers_count_daily')` or just using the model itself? If you could share your test definition that would be helpful too.

Anyway, I've merged the changes in to `development` for testing. Could you try the following in your `packages.yml` file and let me know if it solves things?
```yaml
  - git: "https://github.com/mjirv/dbt-datamocktool.git"
    revision: development
```

**Comment by daveworth** [comment]
Following up I see that in #51 the README adds the `ref('some_table')` to the documentation which seems great!  Thank you!

**Comment by mjirv** [comment]
@daveworth yep, good catch!

I've created a new release w/ this included so the default package from dbt hub should work for you within the next hour.

**Comment by daveworth** [comment]
Thank you @mjirv - we are now on the new release in production and all looks great!  Thanks again!

**Pull request merged**
